### ISSUE TITLE
Prime number 

### ISSUE THREAD

**Issue by Timifakay** [PiyushSuthar/Collatz-Conjecture#1]
I think the reason it ends in a loop is that the division is done using 2 which is the only figure that is both an even number and a prime number. If another even number is used for the division of ń, we may not arrive at a loop. As the smallest even number in the series won't be equal to '2'.

**Comment by Timifakay** [comment]
Suggestion that prime number is the reason we final answer is always a loop.

**Comment by PiyushSuthar** [comment]
That's what the equation is about. Read about it from the links in the readme.

**Comment by Timifakay** [comment]
I read them already. To the f(g) and f(h). The denominator remains 2.
